/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-09-05 12:30:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.courier_002dv1_0_0.public_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class errorPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en-US\" dir=\"ltr\">\n");
      out.write("\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Document Title-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <title>courier | Landing, Responsive &amp; Business Templatee</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Favicons-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/img/favicons/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/img/favicons/favicon-32x32.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/img/favicons/favicon-16x16.png\">\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicons/favicon.ico\">\n");
      out.write("    <link rel=\"manifest\" href=\"assets/img/favicons/manifest.json\">\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/img/favicons/mstile-150x150.png\">\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Stylesheets-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <link href=\"assets/css/theme.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Main Content-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <main class=\"main\" id=\"top\">\n");
      out.write("      <nav class=\"navbar navbar-expand-lg navbar-light fixed-top py-3 d-block\" data-navbar-on-scroll=\"data-navbar-on-scroll\">\n");
      out.write("        <div class=\"container\"><a class=\"navbar-brand\" href=\"index.html\"><img src=\"assets/img/gallery/logo.png\" height=\"45\" alt=\"logo\" /></a>\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"> </span></button>\n");
      out.write("          <div class=\"collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0\" id=\"navbarSupportedContent\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto pt-2 pt-lg-0 font-base\">\n");
      out.write("              <li class=\"nav-item px-2\"><a class=\"nav-link\" aria-current=\"page\" href=\"index.html\">Home</a></li>\n");
      out.write("              <li class=\"nav-item px-2\"><a class=\"nav-link\" href=\"#services\">Our Services</a></li>\n");
      out.write("              <li class=\"nav-item px-2\"><a class=\"nav-link\" href=\"#findUs\">Find Us</a></li>\n");
      out.write("            </ul>\n");
      out.write("            <div class=\"dropdown d-none d-lg-block\">\n");
      out.write("              <button class=\"btn bg-soft-warning ms-2\" id=\"dropdownMenuButton1\" type=\"submit\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fas fa-search text-warning\"></i></button>\n");
      out.write("              <div class=\"dropdown-menu dropdown-menu-lg-end p-0 rounded\" aria-labelledby=\"dropdownMenuButton1\" style=\"top:55px\">\n");
      out.write("                <form>\n");
      out.write("                  <input class=\"form-control border-200\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" style=\"background:#FDF1DF;\" />\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("            </div><a class=\"btn btn-primary order-1 order-lg-0 ms-lg-3\" href=\"#!\">Contact Us</a>\n");
      out.write("            <form class=\"d-flex my-3 d-block d-lg-none\">\n");
      out.write("              <input class=\"form-control me-2 border-200 bg-light\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" />\n");
      out.write("              <button class=\"btn btn-outline-primary\" type=\"submit\">Search</button>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("      <section class=\"py-xxl-10 pb-0\" id=\"home\">\n");
      out.write("        <div class=\"bg-holder bg-size\" style=\"background-image:url(assets/img/gallery/hero-header-bg.png);background-position:top center;background-size:cover;\">\n");
      out.write("        </div>\n");
      out.write("        <!--/.bg-holder-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      <!-- ============================================-->\n");
      out.write("      <!-- <section> begin ============================-->\n");
      out.write("      <section id=\"findUs\">\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"row justify-content-center\">\n");
      out.write("            <div class=\"col-md-8 col-lg-5 mb-6 text-center\">\n");
      out.write("              <h2>Error :(</h2>\n");
      out.write("              <h6>");
      out.print( exception );
      out.write("</h6>\n");
      out.write("              <br><br>\n");
      out.write("              <hr>\n");
      out.write("              <h5>URL을 잘못 입력하셨거나, 시스템 문제일 수도 있습니다.</h5>\n");
      out.write("              <h5>재접속시에도 같은 현상이 반복된다면, 아래 고객센터로 연락주세요.</h5>\n");
      out.write("              <h5>Mobile)010-3368-8958</h5>\n");
      out.write("            </div>\n");
      out.write("              <div class=\"text-center\">\n");
      out.write("                <a class=\"text-light\" href=\"control.jsp?action=list\"><button class=\"btn btn-primary px-5\"><i class=\"fas fa-phone-alt me-2\"></i>처음으로 이동하기</button></a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("       \n");
      out.write("\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("      <section class=\"py-0 bg-1000\">\n");
      out.write("\n");
      out.write("       \n");
      out.write("\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("    </main>\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    End of Main Content-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    JavaScripts-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <script src=\"vendors/@popperjs/popper.min.js\"></script>\n");
      out.write("    <script src=\"vendors/bootstrap/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"vendors/is/is.min.js\"></script>\n");
      out.write("    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=window.scroll\"></script>\n");
      out.write("    <script src=\"vendors/fontawesome/all.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/theme.js\"></script>\n");
      out.write("\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500;600;700;800&amp;display=swap\" rel=\"stylesheet\">\n");
      out.write("  </body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
