/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-09-05 12:32:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.courier_002dv1_0_0.public_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import model.review.*;

public final class lists_005freview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model.review");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\n');
      model.Ordermember.OrderMemberVO ordermemberVO = null;
      synchronized (session) {
        ordermemberVO = (model.Ordermember.OrderMemberVO) _jspx_page_context.getAttribute("ordermemberVO", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (ordermemberVO == null){
          ordermemberVO = new model.Ordermember.OrderMemberVO();
          _jspx_page_context.setAttribute("ordermemberVO", ordermemberVO, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      java.util.ArrayList datas = null;
      datas = (java.util.ArrayList) _jspx_page_context.getAttribute("datas", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (datas == null){
        datas = new java.util.ArrayList();
        _jspx_page_context.setAttribute("datas", datas, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en-US\" dir=\"ltr\">\n");
      out.write("\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Document Title-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <title>courier | Landing, Responsive &amp; Business Templatee</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Favicons-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/img/favicons/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/img/favicons/favicon-32x32.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/img/favicons/favicon-16x16.png\">\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicons/favicon.ico\">\n");
      out.write("    <link rel=\"manifest\" href=\"assets/img/favicons/manifest.json\">\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/img/favicons/mstile-150x150.png\">\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Stylesheets-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <link href=\"assets/css/theme.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Main Content-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <main class=\"main\" id=\"top\">\n");
      out.write("      <nav class=\"navbar navbar-expand-lg navbar-light fixed-top py-3 d-block\" data-navbar-on-scroll=\"data-navbar-on-scroll\">\n");
      out.write("        <div class=\"container\"><a class=\"navbar-brand\" href=\"index.html\"><img src=\"assets/img/gallery/logo.png\" height=\"45\" alt=\"logo\" /></a>\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"> </span></button>\n");
      out.write("          <div class=\"collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0\" id=\"navbarSupportedContent\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto pt-2 pt-lg-0 font-base\">\n");
      out.write("              <li class=\"nav-item px-2\"><a class=\"nav-link\" aria-current=\"page\" href=\"control.jsp?action=logout\">\n");
      out.write("              	로그아웃</a></li>\n");
      out.write("              <li class=\"nav-item px-2\"><a class=\"nav-link\" href=\"insert_review.jsp?onum=");
      out.print(ordermemberVO.getOnum());
      out.write("\">\n");
      out.write("              	리뷰작성</a></li>\n");
      out.write("            </ul>\n");
      out.write("            <div class=\"dropdown d-none d-lg-block\">\n");
      out.write("              <button class=\"btn bg-soft-warning ms-2\" id=\"dropdownMenuButton1\" type=\"submit\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i class=\"fas fa-search text-warning\"></i></button>\n");
      out.write("              <div class=\"dropdown-menu dropdown-menu-lg-end p-0 rounded\" aria-labelledby=\"dropdownMenuButton1\" style=\"top:55px\">\n");
      out.write("                <form action=\"control.jsp\" method=\"post\">\n");
      out.write("                  <input type=\"hidden\" name=\"action\" value=\"search\">\n");
      out.write("                  <input class=\"form-control border-200\" name=\"search\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" style=\"background:#FDF1DF;\" />\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("            </div><a class=\"btn btn-primary order-1 order-lg-0 ms-lg-3\" href=\"control.jsp?action=userreview&onum=");
      out.print(ordermemberVO.getOnum());
      out.write("\">\n");
      out.write("            	내 리뷰보기</a>\n");
      out.write("            <!-- <form class=\"d-flex my-3 d-block d-lg-none\">\n");
      out.write("              <input class=\"form-control me-2 border-200 bg-light\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" />\n");
      out.write("              <button class=\"btn btn-outline-primary\" type=\"submit\">Search</button>\n");
      out.write("            </form> -->\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("      <section class=\"py-xxl-10 pb-0\" id=\"home\">\n");
      out.write("        <div class=\"bg-holder bg-size\" style=\"background-image:url(assets/img/gallery/hero-header-bg.png);background-position:top center;background-size:cover;\">\n");
      out.write("        </div>\n");
      out.write("        <!--/.bg-holder-->\n");
      out.write("\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <!-- ============================================-->\n");
      out.write("      <!-- <section> begin ============================-->\n");
      out.write("      \n");
      out.write("\n");
      out.write("\n");
      out.write("          <div class=\"row justify-content-center\">\n");
      out.write("            <div class=\"col-md-8 col-lg-5 text-center mb-3\">\n");
      out.write("              <h3 class=\"text-danger\">고객 리뷰</h3>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("<!--====================★ 리뷰작성 리스트 ==========================-->\n");
      out.write("\n");
      out.write("<section class=\"py-7\" id=\"services\" container-xl=\"container-xl\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("         <div class=\"row h-100 justify-content-center\">\n");
	for(ReviewVO vo : (ArrayList<ReviewVO>) datas){
	
	
      out.write("\n");
      out.write("            <!--  -->\n");
      out.write("            <div class=\"col-md-4 pt-4 px-md-2 px-lg-3\">\n");
      out.write("              <div class=\"card h-100 px-lg-5 card-span\">\n");
      out.write("                <div class=\"card-body d-flex flex-column justify-content-around\">\n");
      out.write("                  <div class=\"text-center pt-5\">\n");
      out.write("                    <h5 class=\"my-4\">");
      out.print(vo.getTitle() );
      out.write("</h5>\n");
      out.write("                  </div>\n");
      out.write("                  <ul class=\"list-unstyled\">\n");
      out.write("                    <li class=\"mb-2\"><span class=\"me-2\"><i class=\"fas fa-circle text-primary\" style=\"font-size:.5rem\">\n");
      out.write("                    </i></span>");
      out.print( vo.getWriter() );
      out.write("</li>\n");
      out.write("                    <li class=\"mb-2\"><span class=\"me-2\"><i class=\"fas fa-circle text-primary\" style=\"font-size:.5rem\">\n");
      out.write("                    </i></span>");
      out.print(vo.getWdate() );
      out.write("</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <p>");
      out.print(vo.getContent() );
      out.write("</p>\n");
      out.write("                  <div class=\"text-center my-5\">\n");
      out.write("                    <div class=\"d-grid\">\n");
      out.write("                      <button class=\"btn btn-danger hover-top btn-glow border-0\" type=\"submit\">Learn more</button>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- // -->\n");


	}


      out.write("           \n");
      out.write("      </div>\n");
      out.write("      </div>\n");
      out.write("      </section>\n");
      out.write("      <!-- ============================================-->\n");
      out.write("      <!-- <section> begin ============================-->\n");
      out.write("      <section class=\"bg-1000\">\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("              <h2 class=\"fw-bold text-white\">Get an update every week</h2>\n");
      out.write("              <p class=\"text-300\">We ensure that your product is delivered in the safest possible<br />manner, at the correct location, at the right time.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("              <h5 class=\"text-primary mb-3\">SUBSCRIBE TO NEWSLETTER </h5>\n");
      out.write("              <form class=\"row gx-2 gy-2 align-items-center\">\n");
      out.write("                <div class=\"col\">\n");
      out.write("                  <div class=\"input-group-icon\">\n");
      out.write("                    <label class=\"visually-hidden\" for=\"inputEmailCta\">Address</label>\n");
      out.write("                    <input class=\"form-control input-box form-quriar-control text-light\" id=\"inputEmailCta\" type=\"email\" placeholder=\"Enter your mail\" />\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"d-grid gap-3 col-sm-auto\">\n");
      out.write("                  <button class=\"btn btn-danger\" type=\"submit\">Subscribe</button>\n");
      out.write("                </div>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- end of .container-->\n");
      out.write("\n");
      out.write("      </section>\n");
      out.write("      <!-- <section> close ============================-->\n");
      out.write("      <!-- ============================================-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      <!-- ============================================-->\n");
      out.write("      <!-- <section> begin ============================-->\n");
      out.write("      <section class=\"bg-900 pb-0 pt-5\">\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-12 col-sm-12 col-lg-6 mb-4 order-0 order-sm-0\"><a class=\"text-decoration-none\" href=\"#\"><img src=\"assets/img/gallery/footer-logo.png\" height=\"51\" alt=\"\" /></a>\n");
      out.write("              <p class=\"text-500 my-4\">The most trusted Courier<br />company in your area.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-6 col-sm-4 col-lg-2 mb-3 order-2 order-sm-1\">\n");
      out.write("              <h5 class=\"lh-lg fw-bold mb-4 text-light font-sans-serif\">Other links </h5>\n");
      out.write("              <ul class=\"list-unstyled mb-md-4 mb-lg-0\">\n");
      out.write("                <li class=\"lh-lg\"><a class=\"text-500\" href=\"#!\">Blogs</a></li>\n");
      out.write("                <li class=\"lh-lg\"><a class=\"text-500\" href=\"#!\">Movers website</a></li>\n");
      out.write("                <li class=\"lh-lg\"><a class=\"text-500\" href=\"#!\">Traffic Update</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-6 col-sm-4 col-lg-2 mb-3 order-3 order-sm-2\">\n");
      out.write("              <h5 class=\"lh-lg fw-bold text-light mb-4 font-sans-serif\">Services</h5>\n");
      out.write("              <ul class=\"list-unstyled mb-md-4 mb-lg-0\">\n");
      out.write("                <li class=\"lh-lg\"><a class=\"text-500\" href=\"#!\">Corporate goods</a></li>\n");
      out.write("                <li class=\"lh-lg\"><a class=\"text-500\" href=\"#!\">Artworks</a></li>\n");
      out.write("                <li class=\"lh-lg\"><a class=\"text-500\" href=\"#!\">Documents</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-6 col-sm-4 col-lg-2 mb-3 order-3 order-sm-2\">\n");
      out.write("              <h5 class=\"lh-lg fw-bold text-light mb-4 font-sans-serif\"> Customer Care</h5>\n");
      out.write("              <ul class=\"list-unstyled mb-md-4 mb-lg-0\">\n");
      out.write("                <li class=\"lh-lg\"><a class=\"text-500\" href=\"#!\">About Us</a></li>\n");
      out.write("                <li class=\"lh-lg\"><a class=\"text-500\" href=\"#!\">Contact US</a></li>\n");
      out.write("                <li class=\"lh-lg\"><a class=\"text-500\" href=\"#!\">Get Update</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- end of .container-->\n");
      out.write("\n");
      out.write("      </section>\n");
      out.write("      <!-- <section> close ============================-->\n");
      out.write("      <!-- ============================================-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      <!-- ============================================-->\n");
      out.write("      <!-- <section> begin ============================-->\n");
      out.write("      <section class=\"py-0 bg-1000\">\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"row justify-content-md-between justify-content-evenly py-4\">\n");
      out.write("            <div class=\"col-12 col-sm-8 col-md-6 col-lg-auto text-center text-md-start\">\n");
      out.write("              <p class=\"fs--1 my-2 fw-bold text-200\">All rights Reserved &copy; Your Company, 2021</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12 col-sm-8 col-md-6\">\n");
      out.write("              <p class=\"fs--1 my-2 text-center text-md-end text-200\"> Made with&nbsp;\n");
      out.write("                <svg class=\"bi bi-suit-heart-fill\" xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"#F95C19\" viewBox=\"0 0 16 16\">\n");
      out.write("                  <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"></path>\n");
      out.write("                </svg>&nbsp;by&nbsp;<a class=\"fw-bold text-primary\" href=\"https://themewagon.com/\" target=\"_blank\">ThemeWagon </a>\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- end of .container-->\n");
      out.write("\n");
      out.write("      </section>\n");
      out.write("      <!-- <section> close ============================-->\n");
      out.write("      <!-- ============================================-->\n");
      out.write("\n");
      out.write("\n");
      out.write("    </main>\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    End of Main Content-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    JavaScripts-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <script src=\"vendors/@popperjs/popper.min.js\"></script>\n");
      out.write("    <script src=\"vendors/bootstrap/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"vendors/is/is.min.js\"></script>\n");
      out.write("    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=window.scroll\"></script>\n");
      out.write("    <script src=\"vendors/fontawesome/all.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/theme.js\"></script>\n");
      out.write("\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500;600;700;800&amp;display=swap\" rel=\"stylesheet\">\n");
      out.write("  </body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
