/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-09-05 12:38:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.courier_002dv1_0_0.public_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import model.review.*;

public final class user_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model.review");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\n');
      java.util.ArrayList userReviews = null;
      userReviews = (java.util.ArrayList) _jspx_page_context.getAttribute("userReviews", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (userReviews == null){
        userReviews = new java.util.ArrayList();
        _jspx_page_context.setAttribute("userReviews", userReviews, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en-US\" dir=\"ltr\">\n");
      out.write("\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Document Title-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <title>courier | Landing, Responsive &amp; Business Templatee</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Favicons-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/img/favicons/apple-touch-icon.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/img/favicons/favicon-32x32.png\">\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/img/favicons/favicon-16x16.png\">\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicons/favicon.ico\">\n");
      out.write("    <link rel=\"manifest\" href=\"assets/img/favicons/manifest.json\">\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"assets/img/favicons/mstile-150x150.png\">\n");
      out.write("    <meta name=\"theme-color\" content=\"#ffffff\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Stylesheets-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <link href=\"assets/css/theme.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <!--    Main Content-->\n");
      out.write("    <!-- ===============================================-->\n");
      out.write("    <main class=\"main\" id=\"top\">\n");
      out.write("      <nav class=\"navbar navbar-expand-lg navbar-light fixed-top py-3 d-block\" data-navbar-on-scroll=\"data-navbar-on-scroll\">\n");
      out.write("        <div class=\"container\"><a class=\"navbar-brand\" href=\"index.html\"><img src=\"assets/img/gallery/logo.png\" height=\"45\" alt=\"logo\" /></a>\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"> </span></button>\n");
      out.write("            <a class=\"btn btn-primary order-1 order-lg-0 ms-lg-3\" href=\"control.jsp?action=list\">메인화면</a>\n");
      out.write("            <form class=\"d-flex my-3 d-block d-lg-none\">\n");
      out.write("              <input class=\"form-control me-2 border-200 bg-light\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" />\n");
      out.write("              <button class=\"btn btn-outline-primary\" type=\"submit\">Search</button>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("      <section class=\"py-xxl-10 pb-0\" id=\"home\">\n");
      out.write("        <div class=\"bg-holder bg-size\" style=\"background-image:url(assets/img/gallery/hero-header-bg.png);background-position:top center;background-size:cover;\">\n");
      out.write("        </div>\n");
      out.write("        <!--/.bg-holder-->\n");
      out.write("\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <!-- ============================================-->\n");
      out.write("      <!-- <section> begin ============================-->\n");
      out.write("      \n");
      out.write("\n");
      out.write("\n");
      out.write("          <div class=\"row justify-content-center\">\n");
      out.write("            <div class=\"col-md-8 col-lg-5 text-center mb-3\">\n");
      out.write("              <h2 class=\"text-danger\">고객 리뷰</h2>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("<!--====================★ 리뷰작성 리스트 ==========================-->\n");
      out.write("\n");
	
	// 유저의 게시물이 없다면 
	if(userReviews.size()==0||userReviews==null){

      out.write("\n");
      out.write("		   <div class=\"text-center pt-5\">\n");
      out.write("           <h5 class=\"my-4\">저장된 게시물이 존재하지 않습니다.</h5>\n");
      out.write("         </div>\n");

	}

	else{// 있다면 출력
		for(ReviewVO vo : (ArrayList<ReviewVO>) userReviews){
	

      out.write("\n");
      out.write("\n");
      out.write("		<section class=\"py-7\" id=\"services\" container-xl=\"container-xl\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("\n");
      out.write("          <div class=\"row h-100 justify-content-center\">\n");
      out.write("            <!--  -->\n");
      out.write("            <div class=\"col-md-4 pt-4 px-md-2 px-lg-3\">\n");
      out.write("              <div class=\"card h-100 px-lg-5 card-span\">\n");
      out.write("                <div class=\"card-body d-flex flex-column justify-content-around\">\n");
      out.write("                  <div class=\"text-center pt-5\">\n");
      out.write("                    <a href=\"\"><h5 class=\"my-4\">");
      out.print(vo.getTitle() );
      out.write("</h5></a>\n");
      out.write("                  </div>\n");
      out.write("                  <ul class=\"list-unstyled\">\n");
      out.write("                    <li class=\"mb-2\"><span class=\"me-2\"><i class=\"fas fa-circle text-primary\" style=\"font-size:.5rem\">\n");
      out.write("                    </i></span>");
      out.print(vo.getWdate() );
      out.write("</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <p>");
      out.print(vo.getContent() );
      out.write("</p>\n");
      out.write("                  <div class=\"text-center my-5\">\n");
      out.write("                    <div class=\"d-grid\">\n");
      out.write("                      <a href=\"control.jsp?action=editreview&rnum=");
      out.print( vo.getRnum() );
      out.write("\"><button class=\"btn btn-danger hover-top btn-glow border-0\" type=\"submit\">Learn more</button></a>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("           </div>\n");
      out.write("           </div>\n");
      out.write("           </section>\n");

		}
	}


      out.write("           \n");
      out.write("\n");
      out.write("      \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
